export const HandleClick = 'handleClick'
export const HandleHeaderClick = 'handleHeaderClick'
export const HandleHeaderFocusIn = 'handleHeaderFocusIn'
export const HandleListBlur = 'handleListBlur'
export const HandleInput = 'handleInput'
export const HandleReplaceInput = 'handleReplaceInput'
