import { ClassNames } from '@lvce-editor/virtual-dom-worker'

export const {
  Actions,
  Badge,
  Chevron,
  CloseMaskIcon,
  Empty,
  FileIcon,
  FocusOutline,
  Grow,
  Highlight,
  HighlightDeleted,
  HighlightInserted,
  IconButton,
  Label,
  List,
  MaskIcon,
  MaskIconBook,
  MaskIconCaseSensitive,
  MaskIconChevronDown,
  MaskIconChevronRight,
  MaskIconEllipsis,
  MaskIconExclude,
  MaskIconPreserveCase,
  MaskIconRegex,
  MaskIconReplaceAll,
  MaskIconWholeWord,
  MultilineInputBox,
  ScrollBar,
  ScrollBarThumb,
  ScrollBarVertical,
  Search,
  SearchField,
  SearchFieldButton,
  SearchFieldButtonChecked,
  SearchFieldButtonDisabled,
  SearchFieldButtons,
  SearchFieldContainer,
  SearchFieldError,
  SearchHeader,
  SearchHeaderDetails,
  SearchHeaderDetailsExpanded,
  SearchHeaderDetailsExpandedTop,
  SearchHeaderDetailsHeading,
  SearchHeaderTop,
  SearchHeaderTopRight,
  SearchInputError,
  SearchRemove,
  SearchToggleButton,
  SearchToggleButtonExpanded,
  SourceControlBadge,
  ToggleDetails,
  Tree,
  TreeItem,
  TreeItemActive,
  TreeItems,
  Viewlet,
  ViewletSearchMessage,
  ViewletSearchMessageIndented,
} = ClassNames

export const SearchWarningMessage = 'SearchWarningMessage'
