import { expect, test } from '@jest/globals'
import type { SearchState } from '../src/parts/SearchState/SearchState.ts'
import * as Create from '../src/parts/Create/Create.ts'

test('create', () => {
  const state: SearchState = {
    ...Create.create(0, 0, 0, 0, 0, '', ''),
  }
  expect(state).toEqual({
    assetDir: '',
    collapsedPaths: [],
    flags: 0,
    deltaY: 0,
    disposed: false,
    excludeValue: '',
    fileCount: 0,
    finalDeltaY: 0,
    focus: 0,
    focusSource: 1,
    focused: false,
    focusedIndex: -1,
    handleOffset: 0,
    headerHeight: 61,
    height: 0,
    icons: [],
    includeValue: '',
    inputSource: 1,
    itemHeight: 22,
    items: [],
    listFocused: false,
    listFocusedIndex: -1,
    loaded: false,
    matchCount: 0,
    maxLineY: 0,
    message: '',
    minLineY: 0,
    minimumSliderSize: 20,
    replacement: '',
    scrollBarActive: false,
    scrollBarHeight: 0,
    searchId: -1,
    searchResults: [],
    stats: {},
    threads: 0,
    touchDifference: 0,
    touchOffsetY: 0,
    touchTimeStamp: 0,
    uid: 0,
    value: '',
    width: 0,
    workspacePath: '',
    x: 0,
    y: 0,
    listItems: [],
    searchInputErrorMessage: '',
    history: [],
    historyIndex: -1,
  })
})
